version: '3.8'

services:
  nginx:
    image: nginx:1.15.10-alpine
    ports:
      - "9000:8080"
    depends_on:
      - api
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: /bin/sh -c "exec nginx -g 'daemon off;'"

  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    working_dir: /app/api
    depends_on:
      - mysql
    environment:
      - MYSQL_DSN=mysql://root:123asdf@mysql:3306/devastometer?serverVersion=5.7&charset=UTF8
    volumes:
      - ./api/:/app/api

  parser:
    build:
      context: ./
      dockerfile: docker/parser/Dockerfile
    working_dir: /app/parser
    depends_on:
      - mysql
    environment:
      - MYSQL_DSN=mysql://root:123asdf@mysql:3306/devastometer?serverVersion=5.7&charset=UTF8
    volumes:
      - ./parser/:/app/parser

  mysql:
    image: percona:8.0.15-5-centos
    ports:
      - "33066:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123asdf
      MYSQL_DATABASE: devastometer
      LANG: ru_RU.UTF-8
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data: { }
